import streamlit
streamlit.title('My Parents New Healthy Diner')
streamlit.header('Breakfast Menu')
streamlit.text('Idli, Dosa, Upma, Vada')
streamlit.text('🥑🍞Idli,Masala Dosa,Semya Upma,Vada')
streamlit.header('Breakfast Menu')
streamlit.text('🥣 Omega 3 & Blueberry Oatmeal')
streamlit.text('🥗 Kale, Spinach & Rocket Smoothie')
streamlit.text(' 🐔 Hard-Boiled Free-Range Egg')
  streamlit.header('🍌🥭 Build Your Own Fruit Smoothie 🥝🍇') 
